// User Module
export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ERROR_MESSAGE_TIMEOUT = 'USER_ERROR_MESSAGE_TIMEOUT';
export const USER_LOGIN_TOKEN_VERIFICATION_REQUEST =
  'USER_LOGIN_TOKEN_VERIFICATION_REQUEST';
export const USER_LOGIN_TOKEN_VERIFICATION_SUCCESS =
  'USER_LOGIN_TOKEN_VERIFICATION_SUCCESS';
export const USER_LOGIN_TOKEN_VERIFICATION_FAILURE =
  'USER_LOGIN_TOKEN_VERIFICATION_FAILURE';
export const LOADING_REQUEST = 'LOADING_REQUEST';

// Miscellaneous Module
export const MISCELLANEOUS_CREATE_UPDATE_REQUEST =
  'MISCELLANEOUS_CREATE_UPDATE_REQUEST';
export const MISCELLANEOUS_CREATE_UPDATE_SUCCESS =
  'MISCELLANEOUS_CREATE_UPDATE_SUCCESS';
export const MISCELLANEOUS_CREATE_UPDATE_FAILURE =
  'MISCELLANEOUS_CREATE_UPDATE_FAILURE';
export const MISCELLANEOUS_READ_REQUEST = 'MISCELLANEOUS_READ_REQUEST';
export const MISCELLANEOUS_READ_SUCCESS = 'MISCELLANEOUS_READ_SUCCESS';
export const MISCELLANEOUS_READ_FAILURE = 'MISCELLANEOUS_READ_FAILURE';
export const MISCELLANEOUS_DELETE_REQUEST = 'MISCELLANEOUS_DELETE_REQUEST';
export const MISCELLANEOUS_DELETE_SUCCESS = 'MISCELLANEOUS_DELETE_SUCCESS';
export const MISCELLANEOUS_DELETE_FAILURE = 'MISCELLANEOUS_DELETE_FAILURE';
