// User Module
export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ERROR_MESSAGE_TIMEOUT = 'USER_ERROR_MESSAGE_TIMEOUT';
export const USER_LOGIN_TOKEN_VERIFICATION_REQUEST =
  'USER_LOGIN_TOKEN_VERIFICATION_REQUEST';
export const USER_LOGIN_TOKEN_VERIFICATION_SUCCESS =
  'USER_LOGIN_TOKEN_VERIFICATION_SUCCESS';
export const USER_LOGIN_TOKEN_VERIFICATION_FAILURE =
  'USER_LOGIN_TOKEN_VERIFICATION_FAILURE';
