// User Module
// export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ERROR_MESSAGE_TIMEOUT = 'USER_ERROR_MESSAGE_TIMEOUT';

// Miscellaneous Module
export const MISCELLANEOUS_CREATE_UPDATE_REQUEST =
  'MISCELLANEOUS_CREATE_UPDATE_REQUEST';
export const MISCELLANEOUS_CREATE_UPDATE_SUCCESS =
  'MISCELLANEOUS_CREATE_UPDATE_SUCCESS';
export const MISCELLANEOUS_CREATE_UPDATE_FAILURE =
  'MISCELLANEOUS_CREATE_UPDATE_FAILURE';
export const MISCELLANEOUS_READ_REQUEST = 'MISCELLANEOUS_READ_REQUEST';
export const MISCELLANEOUS_READ_SUCCESS = 'MISCELLANEOUS_READ_SUCCESS';
export const MISCELLANEOUS_READ_FAILURE = 'MISCELLANEOUS_READ_FAILURE';
export const MISCELLANEOUS_DELETE_REQUEST = 'MISCELLANEOUS_DELETE_REQUEST';
export const MISCELLANEOUS_DELETE_SUCCESS = 'MISCELLANEOUS_DELETE_SUCCESS';
export const MISCELLANEOUS_DELETE_FAILURE = 'MISCELLANEOUS_DELETE_FAILURE';

// Relationship Module
export const RELATIONSHIP_CREATE_UPDATE_REQUEST =
  'RELATIONSHIP_CREATE_UPDATE_REQUEST';
export const RELATIONSHIP_CREATE_UPDATE_SUCCESS =
  'RELATIONSHIP_CREATE_UPDATE_SUCCESS';
export const RELATIONSHIP_CREATE_UPDATE_FAILURE =
  'RELATIONSHIP_CREATE_UPDATE_FAILURE';
export const RELATIONSHIP_READ_REQUEST = 'RELATIONSHIP_READ_REQUEST';
export const RELATIONSHIP_READ_SUCCESS = 'RELATIONSHIP_READ_SUCCESS';
export const RELATIONSHIP_READ_FAILURE = 'RELATIONSHIP_READ_FAILURE';
export const RELATIONSHIP_DELETE_REQUEST = 'RELATIONSHIP_DELETE_REQUEST';
export const RELATIONSHIP_DELETE_SUCCESS = 'RELATIONSHIP_DELETE_SUCCESS';
export const RELATIONSHIP_DELETE_FAILURE = 'RELATIONSHIP_DELETE_FAILURE';

// Purchase Module
export const PURCHASE_CREATE_UPDATE_REQUEST = 'PURCHASE_CREATE_UPDATE_REQUEST';
export const PURCHASE_CREATE_UPDATE_SUCCESS = 'PURCHASE_CREATE_UPDATE_SUCCESS';
export const PURCHASE_CREATE_UPDATE_FAILURE = 'PURCHASE_CREATE_UPDATE_FAILURE';
export const PURCHASE_READ_REQUEST = 'PURCHASE_READ_REQUEST';
export const PURCHASE_READ_SUCCESS = 'PURCHASE_READ_SUCCESS';
export const PURCHASE_READ_FAILURE = 'PURCHASE_READ_FAILURE';
export const PURCHASE_DELETE_REQUEST = 'PURCHASE_DELETE_REQUEST';
export const PURCHASE_DELETE_SUCCESS = 'PURCHASE_DELETE_SUCCESS';
export const PURCHASE_DELETE_FAILURE = 'PURCHASE_DELETE_FAILURE';

// Inventory Module
export const INVENTORY_CREATE_UPDATE_REQUEST =
  'INVENTORY_CREATE_UPDATE_REQUEST';
export const INVENTORY_CREATE_UPDATE_SUCCESS =
  'INVENTORY_CREATE_UPDATE_SUCCESS';
export const INVENTORY_CREATE_UPDATE_FAILURE =
  'INVENTORY_CREATE_UPDATE_FAILURE';
export const INVENTORY_READ_REQUEST = 'INVENTORY_READ_REQUEST';
export const INVENTORY_READ_SUCCESS = 'INVENTORY_READ_SUCCESS';
export const INVENTORY_READ_FAILURE = 'INVENTORY_READ_FAILURE';
export const INVENTORY_DELETE_REQUEST = 'INVENTORY_DELETE_REQUEST';
export const INVENTORY_DELETE_SUCCESS = 'INVENTORY_DELETE_SUCCESS';
export const INVENTORY_DELETE_FAILURE = 'INVENTORY_DELETE_FAILURE';

// Sales Module
export const SALES_CREATE_UPDATE_REQUEST = 'SALES_CREATE_UPDATE_REQUEST';
export const SALES_CREATE_UPDATE_SUCCESS = 'SALES_CREATE_UPDATE_SUCCESS';
export const SALES_CREATE_UPDATE_FAILURE = 'SALES_CREATE_UPDATE_FAILURE';
export const SALES_READ_REQUEST = 'SALES_READ_REQUEST';
export const SALES_READ_SUCCESS = 'SALES_READ_SUCCESS';
export const SALES_READ_FAILURE = 'SALES_READ_FAILURE';
export const SALES_DELETE_REQUEST = 'SALES_DELETE_REQUEST';
export const SALES_DELETE_SUCCESS = 'SALES_DELETE_SUCCESS';
export const SALES_DELETE_FAILURE = 'SALES_DELETE_FAILURE';

// Inventory Purchase Module
export const INVENTORY_PURCHASE_SUCCESS = 'INVENTORY_PURCHASE_SUCCESS';
export const INVENTORY_PURCHASE_CLEAR = 'INVENTORY_PURCHASE_CLEAR';
